# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d205fc40aaeaed418ca54b2c999d5f70207ec6895ba1be8696b4a070420106222f9ace32380a833797f7744b2e24acc72fe52922c39a0a693bbed0610bf9410

test:
  secret_key_base: 8088d1ae8bdaed6b40a353ce6b9d2e26bd3c2a4b9538eb7890df136c11ee8db3008d737e3b497df32b82f5f126f594e834f9e8d864bef072d2e2d2e402794309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
